### PR TITLE
A self-contained method to run grounding search

### PR DESCRIPTION
**Pull request by jvwong**
- Docker-compose 
  - [x] file with no dependencies/private keys required
  - [x] Need tag/release update so I can hardcode in docker image tag 
- Docs
  - [x] Feature the docker method more prominently in Quick Start
  - [x] explanation of the grounding data available (zenodo) 
    - [x] how to update manually
    - [x] limitations of exiting data (support, use case)
  - [x] Prominently mention the CC0 license for the data in the readme
 

Refs #112

### CODE REVIEW

**Comment by jvwong** [comment]
This still requires that we have some release containing #114 so I can hardcode the image tag into the docker-compose file.

**Comment by maxkfranz** [comment]
Once #119 has been merged in, we can do a release to update the tag in docker

**Comment by jvwong** [comment]
TODO
- [ ] Merge #119
- [ ] Tag
- [ ] Update #117 (this) with tag

**Comment by maxkfranz** [comment]
Ready for merge & tag

**Pull request merged**
