### PR TITLE
FamPlex Part 2:  Datasource

### PR DESCRIPTION
**Pull request by jvwong**
## FamPlex types added

Support for FamPlex entities (N=754). 

Currently, only FamPlex `protein` type is part of the aggregate search and tests. Also, I have included a config variable that enables us to select the entity types we wish to index (see below). This lets us make incremental changes to factoid, factoid-converters etc. Complexes in particular will need some re-working.

###  Types
There are two types: ~~`family`~~`protein`  and `complex`. Type is determined by the triples described in the FamPlex file `relations.csv`: e.g. if `A isa B`, the B is type ~~`family`~~`protein`; else if  `A partof B` then B is a `complex`. In all cases, complex type is dominant over ~~family~~protein.

#### Additional attributes

FamPlex `relations.csv` has triples that make it possible to include extra attributes in the grounding record that could be useful for information and downstream representation (e.g. BioPAX):

- ~~`family`~~`protein`
  - `memberXrefs`: These are the children that represent members of the family
    - e.g. `PRKAA1` and `PRKAA2` genes are part of the `AMPK_alpha` family
- `complex`
  - `componentXrefs`: These are the children of a parent complex
    - e.g. `AMPK_alpha` is part of the `AMPK` complex       

## Test results

Search accuracy, without and with FamPlex:

| FamPlex included  | type | passes | failures |  rate |
| --- | --- | -- | -- | -- | 
|  No  | search | 701 | 58 | 7.6% |
|  Yes  | search | 725 | 62 | 7.9% |

Refs #130 and #137

### CODE REVIEW

**Comment by maxkfranz** [comment]
Is it worth considering, at this point, commonly-used FamPlex names which conflict with other sources (e.g. NCBI)?  Perhaps we should just merge this in to see how it performs in practice on the dev instance?

Maybe @cannin has some suggestions on some conflicts that we should test out on dev?

**Comment by jvwong** [comment]
I'll pull this one in and the accompanying factoid PR, which is trivial (https://github.com/PathwayCommons/factoid/pull/1182).

NB: Right now only `protein` (aka family) will be available. Complexes will take a bit of reworking in factoid.

**Comment by jvwong** [comment]
This is up and running on https://unstable.factoid

**Comment by jvwong** [comment]
Also https://grounding.baderlab.org/search

**Pull request merged**
