### PR TITLE
Improve handling of organisms and strains

### PR DESCRIPTION
**Pull request by maxkfranz**
- Use up-to-date list of strains for E. coli and yeast from NCBI.  The list is hard-coded for now.  
- Add `Organism` class.
- Merge strain IDs for organism ordering.
- Add `organismName` field for entity groundings.
- Merge strain grounding entries under the root taxon ID.

Ref:

- Use NCBI taxonomy database for `entry.organismName` property #43
- Merge entities that are associated with strains #38

### CODE REVIEW

**Comment by maxkfranz** [comment]
Unless anyone has major concerns about merging these changes, let's merge this in sometime today.  Then the CI server will be available for testing from Tuesday onwards.

**Comment by jvwong** [comment]
Just merge this in now. I want to use this in my test reporting...

**Comment by maxkfranz** [comment]
The CI server won't rebuild until this evening.

**Comment by jvwong** [comment]
yeah but I'm doing this locally.

**Comment by maxkfranz** [comment]
Fair enough

**Pull request merged**
