### PR TITLE
db: 'map' between selected database identifiers 

### PR DESCRIPTION
**Pull request by jvwong**
Provides for a new endpoint `/map` that takes one or more identifiers from a database and returns one or more identifiers from a desired database, if they exist. 

Basically this thing looks through the uniprot dbXrefs for the co-occurence of databases the user wishes to map between.  Supported databases include (MIRIAM prefix): ncbigene, refseq, chembl.target, ensembl, genecards, hgnc, reactome, go, interpro, pfam, supfam, uniprot. 

- input
  - `id`:  a string or array of strings that represents identifiers
  - `dbfrom`: MIRIAM prefix of database corresponding to the `id`(s)
  - `dbto`: desired database in which to identify ids
- output
  - Array, one object for each element of `id` 
    - `dbfrom`, `id` from input
    - `dbXrefs` 
      - `db`, `id`

Example use:

IN
```json
{
  "id": [
    "NP_001119584.1"
  ],
  "dbfrom": "refseq",
  "dbto": "ncbigene"
}
```

OUT
```json
[
  {
    "dbfrom": "refseq",
    "id": "NP_001119584.1",
    "dbXrefs": [
      {
        "db": "ncbigene",
        "id": "7157"
      }
    ]
  }
]
```

Refs: https://github.com/PathwayCommons/grounding-search/issues/97

### CODE REVIEW

**Comment by maxkfranz** [comment]
This looks like it's using the existing DB and indexes.  So the lookups may be slow.  As long as users don't need to wait on mapping operations, I'm fine with this approach.

One thing to consider is whether this would bog down the entire grounding service when a conversion is in progress.  The existing searches (i.e. grounding tooltip in Biofactoid) should not be affected, since a user depends on getting those results back instantly.

**Comment by jvwong** [comment]
> This looks like it's using the existing DB and indexes. So the lookups may be slow. As long as users don't need to wait on mapping operations, I'm fine with this approach.

I'm finding it's pretty quick, also I'm using this bulk-like search api called [multisearch](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-multi-search.html)
> 
> One thing to consider is whether this would bog down the entire grounding service when a conversion is in progress. The existing searches (i.e. grounding tooltip in Biofactoid) should not be affected, since a user depends on getting those results back instantly.

By conversion do you mean metin's BioPAX -> Biofactoid? I think all of that should be done on the staging server (master.factoid.baderlab.org) which runs most of its own dependencies (grounding, db, index, app, converter).

**Comment by maxkfranz** [comment]
Great. I just want to avoid having the prod server do anything other than normal searches to keep the UI’s feedback instant

**Review by maxkfranz — APPROVED** [review]

**Comment by metincansiper** [comment]
@jvwong I tried to run the following nodejs script based on the example from you:

```
const fetch = require('node-fetch');

let url = 'http://localhost:3001/map';
let opts = {
  "id": [
    "NP_001119584.1"
  ],
  "dbfrom": "refseq",
  "dbto": "ncbigene"
};

return fetch( url, {
  method: 'POST',
  body: JSON.stringify( opts ),
  headers: {
    'Content-Type': 'application/json'
  }
} )
.then( res => res.json() )
.then( res => console.log( res ) );
```

I got the following error after waiting for a while:

```
(node:13925) UnhandledPromiseRejectionWarning: FetchError: request to http://localhost:3001/map failed, reason: socket hang up
```
.
I run the grounding search service at localhost port 3001.

**Comment by jvwong** [comment]
Did you `npm run clear` and `npm run update`?

**Comment by metincansiper** [comment]
>Did you npm run clear and npm run update?

I just did it. It works now. Thanks!

**Comment by metincansiper** [comment]
@jvwong one thing I realized is that one of the db names I see from dbXrefs is ``MIM`` . However, I could not see that in this mapping (https://github.com/PathwayCommons/grounding-search/pull/99/files#diff-a3f2c4f789f9ceaaca78cf0f04ea5348218b799eba25e0a313d3fa7d6008de52R388).

**Comment by jvwong** [comment]
> @jvwong one thing I realized is that one of the db names I see from dbXrefs is `MIM` . However, I could not see that in this mapping (https://github.com/PathwayCommons/grounding-search/pull/99/files#diff-a3f2c4f789f9ceaaca78cf0f04ea5348218b799eba25e0a313d3fa7d6008de52R388).

Sure I can add that: https://registry.identifiers.org/registry/mim 

I just chose the ones I recognized and were in identifiers.org

**Pull request merged**
