### PR TITLE
Update fibers to v5

### PR DESCRIPTION
**Pull request by maxkfranz**
This allows for `npm install` to work on node@12.

I was annoyed at having to switch back and forth between node@10 and node@12.  This change should allow for either 10 or 12 to be used, whereas only 10 worked before.

### CODE REVIEW

**Review by jvwong — APPROVED** [review]
Yeah i noticed this problem Thanks.

**Comment by jvwong** [comment]
Is it me or is fibers a problem with node 12.X now?

**Comment by maxkfranz** [comment]
It works fine on v10 or v12 locally.  There are warnings re. old packages (e.g. fsevents) and security, deprecations, etc.

Maybe a fresh lock file would help with docker? https://github.com/PathwayCommons/grounding-search/pull/93

**Comment by jvwong** [comment]
Whatever you did in #93 works for me. It was the master.grounding cron job that was complaining so let's see if this works.

**Comment by maxkfranz** [comment]
I had to retry a local build several times, because the uniprot download died midway.  Your error detection won't pick that up, because the file is non-zero in size.

**Comment by maxkfranz** [comment]
```
info:    Processing uniprot data from input/uniprot.xml
Error: Error: undefined:66386677:3: unclosed tag: location
    at SaxesParser.onerror (/Users/user/Documents/workspace/grounding-search/node_modules/saxes/lib/saxes.js:482:11)
```

**Comment by jvwong** [comment]
I manually rebooted the master.grounding and its fine. May wanna look into our ideas about baking in a backup file set

**Comment by maxkfranz** [comment]
Great, #93 may be a good idea anyway to clear out some of those warnings

**Comment by maxkfranz** [comment]
Example warning:

```
node-gyp/12.19.0/include/node/v8.h:3498:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
```

**Pull request merged**
