### PR TITLE
Chunked merging

### PR DESCRIPTION
**Pull request by metincansiper**
Refs #58

- Merged roots by names first then merged them by single synonyms. This affected the behavior. Consider that we have following entities:
```
e1 = { name: 'A' }, e2 = { name: 'B' }, e3 = { name: 'C', synonyms: 'A' }, e4 = { name: 'D', synonyms: 'A' }
```

In the old way e3 and e4 was supposed to be merged into one of e1 or e2 (there was uncertainty about which one to choose). In this case they will not be merged into any of them since after merging by name is completed the root for the name 'A' will not have single synonym.

- The only variable that is maintained for all chunks instead of being cleared after being done with each chunk is ``singleSynonymMergeRefs()`` that keeps tracks of which name is merged into the other one because of single synonym reference. Maintaining it for all chunks makes things a lot easier and do not cause memory problems since maximum size of it is around 176-186. It varies and I could not figure out yet about the reason why.

- In the previous implementation was considering circular single synonym references case. Did not consider it in this implementation and the current ncbi data does not have such a case. However, if it is desired to handle circular references I can manage to do it (probably would need to maintain a new map based on ``singleSynonymMergeRefs()``. New map would keep the eventually merged entities instead of the next one in the chain.). However, if it is not an expected case at all I would rather keeping it as is.

- I realized that the eventual number of entities in database changes after each run (like 23718536 after one run and 23718547 after the other one). I would not foresee it. I would expect to be able to predict the eventual number of entities since we initially merge the roots by name then by single synonyms. My guess is that it may be related to that size of ``singleSynonymMergeRefs()`` varies as I mentioned above. I may need to debug it more to see if there is a edge case missing there. In the sample tests I am able to guess the number of eventual entities and the related test is successful. There may be an edge case that is not available in the sample file but emerging in the actual file.

- I did not try to see if the script would work faster by querying organization by organization or all together while searching the descendants yet (@maxkfranz talking about the thing that you suggested in video call). I plan to do it and make a related update if needed. However, I think it must be fine anyways because  merging strains still does not cause a big latency in script. It takes around 80-90 secs if I am not wrong, which is most probably way slower then the previous version as it would be expected but it is relatively a short time considering the run time of the whole script.

- Number of failing test cases is 75 after the changes, I suppose it was 76 before. Not sure but it may not be 75 (I may have seen 76 as well not sure) always as the eventual number of entities in database is not stable.

### CODE REVIEW

**Comment by maxkfranz** [comment]
Note that in my pseudocode, I wrote it in a synchronous style.  You can do something similar with async/await syntax.

**Comment by metincansiper** [comment]
@maxkfranz looks like the typo you found out is very important and would possibly be (very likely but not sure yet) the reason why the current implementation of this PR unexpectedly yields different number of entities in each run.

About updating the db immediately I am nearly sure that it will make update operation much slower then plain NCBI update. It would probably be fine with another database but not in elasticsearch. Because to ensure that the next query result will be based on our previous update we need to refresh the index after the update. Which is an expensive operation to make after each update. During initial implementation of this PR I tried to update the index immediately only for root marking/promotions. Even that makes things so much slower for the sample file (probably made merging phase slower than the plain ncbi update itself).

The approach of not separating between descendants and roots upon querying makes sense to me and agree that it would make something easier. However, I it yields fallowing concerns related to single synonyms from my side:

- I guess in the past we were merging the entity A into B if A has single synonym which is A. New algorithm merges them if B has a single synonym which is A as well. That is fine to me as long as it is what is expected. And I believe that this is a crucial detail in the algorithm that you proposed.
- I assume that the following from your pseudo code is done only if there is a single synonym (I mean after checking the root has a single synonym)  ``root.singleSynonym = root.synonyms[0]``. With this assumption consider that we have the fallowing entities:
```
E1 -> { name: 'A'}, E2 -> {name: 'B', synonyms: ['A'], E3 -> {name: 'B'}
```
The resulting index may change a lot according to what we get from the db. For example if E1 is the first obtained entity and the E2 is the second one the the merged index will be like:
```
E1 -> { name: 'A', synonyms: ['A', 'B'], root: true}, E3 -> {name: 'B', root: true}
```

Where we have marked E1 as root initially. Then merged E2 into E1 since the single synonym of E2 matches the name of root E1. Then we could not find any existing root for E3 and so just marked E3 as root.

To me the big problem here is that E2 and E3 are not merged together though they have the same name. I was thinking that merging by name is the first important rule. Do you agree? If you agree I can think of a way of handling that. In the previous implementation I was keeping the single synonym merge references map for similar but different reasons. This case may be more complicated.

**Comment by metincansiper** [comment]
One way maybe adding a ``names`` field that keeps the name of root itself and the entities that are merged into it and checking ``names`` instead of ``name`` upon finding root.

**Comment by metincansiper** [comment]
Also there is one more edge case. If we have the fallowing entities:
```
E1 -> { name: 'A' }, E2 -> { name: 'B', synonyms: 'A' }, E3 -> { name: 'C', synonyms: 'B' }
```

If we pull entities in order of E1, E2, E3 then after merge E1 and E2 will be merged together while E3 will be separate from them. While the order of E2, E3, E1 would merge them all together. 

I suppose maintaining and using the ``names`` field would solve this case as well.

**Comment by maxkfranz** [comment]
> About updating the db immediately I am nearly sure that it will make update operation much slower then plain NCBI update.

OK, I didn't expect it to be that slow.  If that the case, then we need to use the existing queueing approach.

> I assume that the following from your pseudo code is done only if there is a single synonym

Yes

> E1 -> { name: 'A'}, E2 -> {name: 'B', synonyms: ['A'], E3 -> {name: 'B'}

The junk entries we've seen so far would be more like this:

```
E4 => { name: 'B', synonyms: ['A'] }
```

So E4 matches E1.

Anyway, your `names` approach should work for the cases you mentioned.  It makes the matching transitive, so there is a risk of unintentional merges.  However, it's probably OK based on the cases we've seen and it may make things simpler.

The approach in the pseudocode should be compatible as long as the different multiplicity of `names` is taken into account (e.g. any `names.some(n => n === someOtherName)` versus `singleSynonym === someOtherName` ).

It would be great if the merging logic could be simplified like the pseudocode, even if we don't use the immediate DB updates.  It may help to simplify things, identify bugs, etc.

**Comment by metincansiper** [comment]
@maxkfranz There is one thing realized during debugging and that could be kind of problematic (Note that I am not able to implement the pseudo code as is since I cannot update the database immediately but I am trying to have the exactly same behaviuor).

Consider that we have the fallowing entries:

```
let singleSynonymEntries = [
    {
      'namespace': 'ncbi',
      'type': 'protein',
      'id': '1',
      'organism': '562',
      'name': 'A',
      'synonyms': [
        'B'
      ]
    },
    {
      'namespace': 'ncbi',
      'type': 'protein',
      'id': '2',
      'organism': '562',
      'name': 'B',
      'synonyms': [
        'C'
      ]
    },
    {
      'namespace': 'ncbi',
      'type': 'protein',
      'id': '3',
      'organism': '562',
      'name': 'B',
      'synonyms': [
      ]
    },
    {
      'namespace': 'ncbi',
      'type': 'protein',
      'id': '4',
      'organism': '562',
      'name': 'C',
      'synonyms': [
        'D'
      ]
    },
    {
      'namespace': 'ncbi',
      'type': 'protein',
      'id': '5',
      'organism': '562',
      'name': 'D',
      'synonyms': [
      ]
    },
    {
      'namespace': 'ncbi',
      'type': 'protein',
      'id': '6',
      'organism': '562',
      'name': 'd',
      'synonyms': [
        // 'B'
      ]
    }
  ];
```

And our merging code reads the entries from database in order of ``1``,`` 3``,`` 4``,`` 5``, ``6``,`` 2`` (I am listing the ids here). In that case ``1``,`` 2``, ``3`` will be merged together on one side and on the other side ``4``,`` 5``, ``6`` will be merged together. However, these two groups will not be merged into each other and we will end up with having 2 roots after merging operation is done.

In this case we end up with having 2 groups because the entity which is expected to merge two groups is ``2`` and it is read at the very end. However, if it was read right after ``1`` we would end up with having only one single root where all the other are merged into at the end. The previuos version of code would give us only one entity after each run consistently. 

Do you think it is okay to have such a behaviour and inconsistency?

**Comment by maxkfranz** [comment]
Shouldn't all of those entries be equal?  Our definition of equality is basically this:

- name is matchingEnt.name
- singleSynonym is matchingEnt.name
- name is matchingEnt.singleSynonym, if matchingEnt.singleSynonym exists
- singleSynonym is matchingEnt.singleSynonym, if matchingEnt.singleSynonym exists

Where `singleSynonym` would be an array given your `names` strategy -- since you could have two single synonyms, for example, when merging two entities together.

**Comment by metincansiper** [comment]
@maxkfranz instead of having a ``singleSynonyms`` array I preferred to improve ``names`` so that it would keep the ``singleSynonym`` values besides the ``names`` values. It must do the same thing. 

Doing so solves one single problem. Consider that we have the following entities:
```
E1 -> {name: 'A', singleSynonym: 'B'}
E2 -> {name: 'B', singleSynonym: 'C'}
E3 -> {name: 'C'}
```
In this case if I add ``singleSynonym`` fields as well to ``names`` all of E1, E2, E3 will be merged at the end. On the other hand if I do not add ``singleSynonym`` fields to ``names`` and we get the entries from the db in order of ``E1`` ``E2`` ``E3`` then E3 will not be merged into the others at the end.

That is great but the bad part is that it is the only problem that is solved by making that change. The original problem still remains mostly. 

If we have the ``singleSynonymEntries`` that I attached to my previous comment and the entries are read from the db in the same order that I mentioned there the problem will remain. The big problem there was that  the updated merge algorithm reads one entity at a time and merges it to its root as needed. Until we get ``2`` from database ``1`` and ``3`` was merged in one side and ``4`` ``5`` ``6`` were merged in other side. No reason to merge them as long as we do not have ``2``. However, at the end we are having ``2`` which can normally be merged into any of the two groups. It is being merged into group of ``1`` and ``3`` since the implementation details favors the matching names over the other cases.  However, the nature of algorithm has nothing to merge these two groups since ``2`` would be merged into any of them. Therefore, we end up with having 2 different groups anyways.

Do you think it is fine to have this behaviour in merging?

**Comment by maxkfranz** [comment]
With our previous definition of equivalency and our universal merge operation, you should have the flexibility to handle things either bottom-up or top-down.

With the bottom-up approach, you look at each entity, E, that is unmarked (unhandled) and ask, "Which one entity should I merge E into?".  With this approach, you may need to make multiple passes -- where the exit condition is a pass with no merges made. 

With the top-down approach, you look at each entity, E, that is unmarked and ask, "What are all the other entities that I should merge into this one?"  With this approach, you have to make a new query each time your `names` field grows.

**Comment by metincansiper** [comment]
Yes, it looks doable. I wanted to make sure that what we already have is not enough before making that kind of change. I will probably go for the multiple passes approach.

**Comment by metincansiper** [comment]
@maxkfranz I was thinking that this algorithm should always yield the same number of entities in db (given the same input file) since we make merge by checking all possible name/single synonym combinations. However, the current code does not work like that. The number of entities that remains in db after merge may change in different runs. 

Would you expect to have the same number of entities in each run as well? Maybe I am missing some point about the algorithm that actually makes having different number of entities in different runs expected?

**Comment by metincansiper** [comment]
Probably it is supposed to be the same in each run. I added a new test (not committed yet) to see if there is any name repeated in ``names`` field (or union of ``name``, ``singleSynonym`` if ``names`` is not set) of multiple entries at the end. And there were a few repetitions for the test file. Which (I guess) indicates that there is something wrong with the implementation.

**Comment by metincansiper** [comment]
Yes, it was just about me forgetting to refresh the index somewhere. After fixing that no duplication happened and merge operation yielded the same number of entries in each run for the sample file (have not tried for the actual file yet).

**Comment by maxkfranz** [comment]
>  I was thinking that this algorithm should always yield the same number of entities in db (given the same input file) since we make merge by checking all possible name/single synonym combinations. However, the current code does not work like that. The number of entities that remains in db after merge may change in different runs.

If there can be ordering differences on each run (i.e. elasticsearch gives a different sorted result), then you could have cases like your example where the entities are disjoint for a single run.  With the bottom-up approach, you need to do multiple passes/runs until the count stabilises.  In your example, the two disjoint roots from run 1 would be merged together in run 2.

**Comment by metincansiper** [comment]
>If there can be ordering differences on each run (i.e. elasticsearch gives a different sorted result), then you...
Yes, actually this was what I was doing but as I mentioned it was not working initially because I omitted to refresh index at somewhere where it was a must. After fixing that it worked well for the sample data. However, for the actual data even though I waited quite long time the merge has never been completed. BTW my computer is slower than normal lately. Even the normal ncbi update (before merging) runs slower than ever. Therefore, it could have been finished in an other computer after waiting for the same time. Not sure about that but I can tell that I am sure that a lot of passes have been done in that time but even that was not enough for the algorithm to exit. 

Therefore, I implemented an alternative way. I considered that the main problem was that our way to decide whether to merge entities was not transitive and we could make it transitive by deciding which names/single synonyms are related to each other (so the entities having them must be merged). Therefore, initially I filled an array that keeps the ``relatedNameSets()``. If an entity has name of ``n`` and singleSynonym of ``s`` then ``n`` and ``s`` must be located inside the same set, also the same string cannot be located inside more than one set. You can see the details in code. After filling that array I run the algorithm discussed here based on that. In that way I did not need to maintain ``names`` field as well. 

It worked perfectly for the sample file. The test that checks if the number of entities is as expected after merge passed. Also, I added a test to check if the ``ids`` field has the expected things to see if what is correct entries are merged together. That tests passes as well. 

For the actual ncbi file things works near to expected but only one unexpected thing is that. In one run of ``update:ncbi`` there was 23684916 entries, after the other one there was 23684918 entries. The difference is only 2.  I guess it would be a very edge case that is missing or a very well hidden bug.

About the size of ``relatedNameSets()`` that I maintain. It is maintained per root strain organism. Its flat size was if I am not wrong 7000-8000 names for one root organism and around 49000-50000 for the other one. Here the bigger one matters. Lets say that the avarage name size is 20 characters, from my experiences with ``Buffer.byteLength()`` for at least most (most probably even the all) of our possible characters from input file the strings will consume as many Bytes as their length. Which means that the total space on ram will be 1 mb. Even we assume that avarage as 100 instead of 20 it would make 5mb. I beleive that these will not be important sizes on ram.

**Comment by metincansiper** [comment]
BTW after the changes the time performance of merge is decreased. I mistakenly deleted my records but I remember it like taking as 4 times as the plain ncbi update. However, ratios may not be realistic for one single run (and as I mentioned my computer is problematic lately). We may try playing with chunk size to try making it faster.

**Comment by maxkfranz** [comment]
I tried running this branch on my machine, and it seems to have a problem with the promises.  The main update promise must be resolved early, because I see the message "Finished updating ncbi data" with Elasticsearch and Node still running with high CPU usage.  The command `npm run update:ncbi` doesn't end either, as I don't get the cursor back.

**Comment by maxkfranz** [comment]
On the master branch, a fresh `npm run update:ncbi` takes 10 minutes on my desktop.

On this branch, it runs for over an hour without finishing.  My desktop is about 3x faster than a typical macbook, so this could make local testing prohibitively expensive.

Merging at the index level might not be pragmatic for this iteration.  I'll look into processing at the aggregate search level instead.

**Comment by metincansiper** [comment]
>I tried running this branch on my machine, and it seems to have a problem with the promises. The main update promise must be resolved early, because I see the message "Finished updating ncbi data" with Elasticsearch and Node still running with high CPU usage. The command npm run update:ncbi doesn't end either, as I don't get the cursor back.

I think it is just about the timing of printing the info of "Finished updating ncbi data". It is printed by the ``updateEntriesFromFile()`` of ``processing.js`` right after entries are saved to database from the file.  ``updateEntriesFromFile()`` is called by each datasource files. ``ncbi.js`` calls it and then attempts to merges the strains right after the related promise is resolved. Therefore, it is something expected because merging strains is just triggered right after that message is printed out.

It was always working like this but since it was working faster and most of the time we left the script running on background probably you were not recognizing that.

**Comment by metincansiper** [comment]
> On the master branch, a fresh npm run update:ncbi takes 10 minutes on my desktop.

@maxkfranz are you still seeing the message of "Finished updating ncbi data" after 10 minutes in this branch (though it keeps running for merging strains)?

**Pull request closed without merging**
