### PR TITLE
Remove node fibers & better Greek letter support

### PR DESCRIPTION
**Pull request by maxkfranz**
- Node fibers was removed
  - It doesn't use separate threads anymore
  - It just uses a simple Promise wrapper
  - We may want to update the aggregate.js file to use a separate thread for processing, but I left it simple for now
  - Should support newer versions of node
  - I couldn't run the service on my Mac at all without removing this, so it's in the same PR as the Greek letter support
- Better Greek letter support
  - Support alpha, beta, gamma, delta, epsilon, zeta
  - Support written out form, e.g. PPAR-gamma
  - Support Latin single letter, e.g. PPARg
  - Support Greek single letter, e.g. PPARγ

Ref:

- #145 
- #149

### CODE REVIEW

**Comment by maxkfranz** [comment]
Affects docs like this one: https://biofactoid.org/document/fad2b244-6323-4115-a84d-ecd957a6f9ef

LncRNA Snhg3 aggravates hepatic steatosis via PPARγ signaling.

**Comment by maxkfranz** [comment]
@jvwong, I didn't add any new test cases and only tested this manually.  Feel free to add test cases, if you like.

**Comment by jvwong** [comment]
I wanted to compare if there was any significant timing changes in `npm run restore` but noticed that my iMac couldn't even install the master branch anymore (bunch of node-gyp errors) where this one was OK, so I would merge this in.

| branch | `npm run restore` (s) |  search (ms) | get (ms) |
|--------|-----------------------|------------|----------|
| `master` |  |  |  |
| `modern-and-greek` | 193 | 150 |  25 |

**Review by jvwong — APPROVED** [review]
Restore and searc/get work well for me. Would merge to avoid errors with installing master.

**Comment by maxkfranz** [comment]
Merged

**Pull request merged**
