### PR TITLE
sars-cov-2 tweaks

### PR DESCRIPTION
**Pull request by maxkfranz**
Improves performance of 'SARS-Cov-2 Support #73'

- Patch file support c2b5bae
- Organism reordering  e5aeed1
- Single character fuzziness disabled 97f06df

Tagging @cannin re. script analysis of synonym overlap.  See e5aeed1

@jvwong, add other synonym patches that you think would be useful to [patches.js](https://github.com/PathwayCommons/grounding-search/blob/97f06df12de12308996dfb3aa2fe065a5ac75fd6/src/server/db/patches.js).

### CODE REVIEW

**Comment by jvwong** [comment]
Wanted to add to the test harness - someone posted this review which is a decent start (https://science.sciencemag.org/content/369/6503/510). Also see UniProt https://covid-19.uniprot.org/uniprotkb?query=*&facets=other_organism:Severe%20acute%20respiratory%20syndrome%20coronavirus%202

**Comment by jvwong** [comment]
The test failure report below. Important column is 'rank' (last). 

- Most times the actual rank is in the top 2, likely a choice between gene and protein
- The only thing that sticks out is 'N' (rank 7), which probably gets mixed up with a bunch of chemicals

|  title | state | text | expected.namespace | expected.id | actual.namespace | actual.id | organismOrdering | rank |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  search ORF1ab 2697049 | failed | ORF1ab | ncbi | 1796318597 | ncbi | 43740578 | [2697049] | 1 |
|  search spike 2697049 | failed | spike | ncbi | 43740568 | ncbi | 1796318598 | [2697049] | 1 |
|  search S 2697049 | failed | S | ncbi | 1796318598 | ncbi | 43740568 | [2697049] | 2 |
|  search envelope 2697049 | failed | envelope | ncbi | 43740570 | ncbi | 1796318600 | [2697049] | 1 |
|  search E 2697049 | failed | E | ncbi | 1796318600 | ncbi | 43740570 | [2697049] | 3 |
|  search membrane 2697049 | failed | membrane | ncbi | 43740571 | ncbi | 1796318601 | [2697049] | 1 |
|  search nucleocapsid 2697049 | failed | nucleocapsid | ncbi | 43740575 | ncbi | 1798174255 | [2697049] | 1 |
|  search N 2697049 | failed | N | ncbi | 1798174255 | ncbi | 43740575 | [2697049] | 7 |
|  search ORF8 2697049 | failed | ORF8 | ncbi | 1796318604 | ncbi | 43740577 | [2697049] | 1 |
|  search ORF3a 2697049 | failed | ORF3a | ncbi | 1796318599 | ncbi | 43740569 | [2697049] | 1 |
|  search ORF6 2697049 | failed | ORF6 | ncbi | 1796318602 | ncbi | 43740572 | [2697049] | 1 |
|  search ORF10 2697049 | failed | ORF10 | ncbi | 1798174256 | ncbi | 43740576 | [2697049] | 1 |
|  search pp1a 2697049 | failed | pp1a | ncbi | 1802476803 | ncbi | 43740578 | [2697049] | 1 |
|  search pp1ab 2697049 | failed | pp1ab | ncbi | 1796318597 | ncbi | 43740578 | [2697049] | 1 |
|  search spike 2697049 | failed | spike | ncbi | 43740568 | ncbi | 1796318598 | [2697049] | 1 |
|  search ORF1ab 2697049 | failed | ORF1ab | ncbi | 1796318597 | ncbi | 43740578 | [2697049] | 1 |
|  search ORF1a 2697049 | failed | ORF1a | ncbi | 43740578 | ncbi | 1802476803 | [2697049] | 2 |
|  search membrane protein 2697049 | failed | membrane protein | ncbi | 43740571 | ncbi | 1796318601 | [2697049] | 1 |
|  search M 2697049 | failed | M | ncbi | 1796318601 | ncbi | 43740571 | [2697049] | 2 |
|  search nucleocapsid protein 2697049 | failed | nucleocapsid protein | ncbi | 43740575 | ncbi | 1798174255 | [2697049] | 1 |
|  search N 2697049 | failed | N | ncbi | 1798174255 | ncbi | 43740575 | [2697049] | 7 |
|  search ORF6 2697049 | failed | ORF6 | ncbi | 1796318602 | ncbi | 43740572 | [2697049] | 1 |

**Comment by maxkfranz** [comment]
> Most times the actual rank is in the top 2, likely a choice between gene and protein

If these are protein coding genes, what about amending the patch file to merge those groundings?  If you have protein X (sars-covid-2) and gene X, they're the same to the user anyway.  The only difference is the (gene | protein | dna | rna) select box.

**Comment by jvwong** [comment]
I believe most or all of the failures are probably because I created tests that erroneously pointed at the gene rather than the protein. You can't merge gene/protein because the gene can point to an 'sub-genomic' RNA etc.

**Comment by maxkfranz** [comment]
There may be other issues around including both NCBI protein entries and NCBI protein entries.  For instance, an NCBI protein grounding might not be applicable to the (gene | dna | rna | protein) selector.

For resolving within-organism conflicts, we may have something like a quick question interface for exact matches.  E.g. 

```
Which do you mean?

[ Foo                ]    [ Foo                ]
[ synonym1, synonym2 ]    [ synonym3, synonym4 ]
```

An example of a similar conflict for an organism other than sars-cov-2 is "p53" for drosophila:

- p53: Dp53...
- p53: betaTub60D...
- p53: hth ...

**Comment by jvwong** [comment]
I think I know what to do for this case: 

- Keep all the genes as is
- Drop proteins for which a 1-to-1 relationship with gene does not exist (i.e. `NSP1-NSP16`)

**Comment by jvwong** [comment]
There's a filterFunction that could read from a blacklist on index.

https://github.com/PathwayCommons/grounding-search/blob/c59e7fc07abdb7d8c9a14bbc5e93b02ca95871fd/src/server/datasource/processing.js#L153

**Comment by maxkfranz** [comment]
That sounds good.

Maybe something along the lines of this:

```js
const entries = parse( data ).filter( includeEntry ).filter( includeWrtBlacklist ).map( processEntry );
```

The filters should probably be separate, since `includeEntry` is per provider (datasource).

**Comment by jvwong** [comment]
Two 'failed' tests, totally understandable cases

|  title | state | text | expected.namespace | expected.id | actual.namespace | actual.id | organismOrdering | rank |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  search pp1a 2697049 | failed | pp1a | ncbi | 1802476803 | ncbi | 43740578 | [2697049] | 1 |
|  search ORF1ab 2697049 | failed | ORF1ab | ncbi | 1802476803 | ncbi | 43740578 | [2697049] | 1 |

**Comment by maxkfranz** [comment]
OK, then I think this may be good enough to just merge in for now so people can try it out live.

**Pull request merged**
