### PR TITLE
ChEBI: Skip empty entries and make sure there's an id

### PR DESCRIPTION
**Pull request by jvwong**
Refs #67

### CODE REVIEW

**Comment by maxkfranz** [comment]
Looks good.

Just wondering: Is there a straightforward way to identify errors like these when docker is building?  I suppose right now the build just goes forward even when these errors happen

**Comment by jvwong** [comment]
> Looks good.
> 
> Just wondering: Is there a straightforward way to identify errors like these when docker is building? I suppose right now the build just goes forward even when these errors happen

Yes: The `indexer` container will have a `STATUS` of `Exited (1)...`:

```sh
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED              STATUS                      PORTS                                                         NAMES
fa66bc432784        pathwaycommons/grounding-search:latest                "./wait-for-elastics…"   About a minute ago   Exited (1) 27 seconds ago                                                                 indexer_container
b2094f22a821        docker.elastic.co/elasticsearch/elasticsearch:6.7.2   "/usr/local/bin/dock…"   About a minute ago   Up About a minute           9200/tcp, 9300/tcp                                            index_container
```

**Comment by jvwong** [comment]
Sorry if you meant when building the image, there's no call to `npm update` at all so not right now. We'd have to try to index it

**Comment by maxkfranz** [comment]
> Sorry if you meant when building the image, there's no call to npm update at all so not right now. We'd have to try to index it

OK, good to know.  It would be nice if we could catch errors as early in the process as possible, but it's not worth it if it makes things more complex.

**Pull request merged**
